const zh = {
  title:'把 Gmail 配置，安全带到新邮箱', subtitle:'免费开源 · 本地处理 · 不上传邮件。此工具生成迁移配置，不搬运邮件。', language:'界面语言', privacy:'全程本地 · 零上传',
  steps:['选择目标','导入文件','检查结果','文件夹映射','导出'], back:'上一步', next:'下一步', target:'目标邮箱', targetHelp:'能力列表仅供保守判断，未在真实账户验证。请在目标邮箱测试后再启用。', unverified:'未经真实账户验证', manual:'手工重建', notes:'目标说明（原始语言）', docs:'查看服务商文档',
  importTitle:'选择 Gmail 导出文件', importHelp:'选择 mailFilters.xml、MBOX、ZIP 或已解压文件夹。可以只导入规则或只分析邮件。', files:'选择文件', folder:'选择文件夹', limits:'ZIP 最大 512 MiB，解压安全限制另计；大邮箱请先解压。XML 最大 10 MiB。不支持的文件会给出说明。', reset:'清空当前数据', cancel:'取消分析', busy:'正在本地分析', expanding:'正在检查文件和压缩包…', importDone:'分析完成', cancelled:'已取消；此前完成的结果已保留。', failed:'导入失败', duplicate:'已导入相同文件标识，跳过（按路径、大小和时间识别）', noData:'请先成功导入 XML 或 MBOX。', sources:'已完成的来源', size:'大小', source:'来源', records:'记录', progress:'分析进度',
  reviewTitle:'检查转换结果', reviewHelp:'近似规则默认禁用；已跳过的规则不会生成活动代码。状态不是服务商兼容认证。', filter:'规则状态筛选', all:'全部', converted:'已转换', approximate:'近似 — 默认禁用', skipped:'已跳过', rules:'过滤规则', folders:'用户文件夹', senders:'历史发件地址候选', rule:'规则', status:'状态', details:'原始规则与技术诊断', technical:'技术诊断可能保留原始语言。', noneRules:'没有过滤规则；仍可导出邮件分析结果。', senderHelp:'地址仅由 Sent 标签或明确已发送文件名推断，并非 Gmail 设置清单。次数受去重上限、缺失 ID 和导出范围影响；不推断置信度或服务商。', email:'地址', count:'邮件数', noneSenders:'没有识别到历史发件地址。', warnings:'输入警告',
  mappingTitle:'确认文件夹映射', mappingHelp:'修改会同时更新 Sieve 与 folders.json。输入目标邮箱中实际存在或准备创建的名称。嵌套 / 分隔符须自行核对。', original:'Gmail 标签', destination:'目标文件夹', archive:'归档目标', trash:'垃圾箱目标', notesColumn:'备注', emptyMapping:'没有用户标签；可直接继续。', invalidFolder:'文件夹名不能为空、仅包含空白或含控制字符。', collision:'文件夹名称冲突（忽略大小写、Unicode 规范化和首尾空格）。', reservedFolder:'用户文件夹不能使用目标服务商的保留名称。', specialConflict:'用户标签 Archive/Trash 与特殊动作使用相同映射键；请先在原规则中重命名标签。', mappingBlocked:'请修正文件夹映射后再导出。',
  exportTitle:'导出迁移材料', exportHelp:'下载不是迁移完成。先建立文件夹，检查报告，测试匹配与不匹配的邮件，再启用规则。', active:'已转换规则', disabled:'禁用或跳过', sieve:'下载 rules.sieve', folderDownload:'下载 folders.json', senderDownload:'下载 senders.csv', gaps:'下载 gaps.md', recipe:'下载手工配方', guide:'下载迁移指南', copy:'复制 Sieve', copied:'已复制', copyFailed:'复制失败，请下载文件。', noActive:'当前没有可直接启用的规则。Sieve 可能仅含注释，请阅读报告。', recipeHelp:'此目标使用手工配方，不提供可导入 Sieve。',
  footer:'不登录邮箱、不上传数据、不自动修改目标邮箱。关闭页面后当前分析结果不会被保存。',
};
const en = {
  title:'Take your Gmail settings with you', subtitle:'Free and open source · Local processing · No mail uploads. This tool prepares settings; it does not move messages.', language:'Interface language', privacy:'Local only · No uploads',
  steps:['Target','Import','Review','Folder mapping','Export'], back:'Back', next:'Next', target:'Destination mailbox', targetHelp:'Capabilities are conservative candidates, not verified against a real account. Test before enabling.', unverified:'Not account-tested', manual:'Manual setup', notes:'Target notes (original language)', docs:'Provider documentation',
  importTitle:'Select Gmail export files', importHelp:'Choose mailFilters.xml, MBOX, ZIP, or an extracted folder. Rules-only and mail-only imports are supported.', files:'Choose files', folder:'Choose folder', limits:'ZIP input up to 512 MiB; separate expansion limits apply. Extract large mailboxes first. XML up to 10 MiB. Unsupported inputs are reported.', reset:'Clear current data', cancel:'Cancel analysis', busy:'Analyzing locally', expanding:'Checking files and archives…', importDone:'Analysis complete', cancelled:'Cancelled; previously completed results are retained.', failed:'Import failed', duplicate:'Already imported this file identity; skipped (path, size and timestamp comparison)', noData:'Import a valid XML or MBOX first.', sources:'Completed sources', size:'Size', source:'Source', records:'Records', progress:'Analysis progress',
  reviewTitle:'Review conversion results', reviewHelp:'Approximate rules are disabled by default. Skipped rules emit no active code. Status is not provider certification.', filter:'Filter by rule status', all:'All', converted:'Converted', approximate:'Approximate — disabled', skipped:'Skipped', rules:'Filter rules', folders:'User folders', senders:'Historical sender candidates', rule:'Rule', status:'Status', details:'Original rule and technical diagnostics', technical:'Technical diagnostics may remain in their original language.', noneRules:'No filter rules. Mail analysis results can still be exported.', senderHelp:'Addresses are inferred only from Sent labels or explicit sent-mail filenames, not Gmail settings. Counts depend on deduplication limits, missing IDs and export scope; no confidence or provider is inferred.', email:'Address', count:'Messages', noneSenders:'No historical sender identities found.', warnings:'Input warnings',
  mappingTitle:'Confirm destination folders', mappingHelp:'Edits update both Sieve and folders.json. Use actual or planned destination names. Confirm the / hierarchy delimiter with your provider.', original:'Gmail label', destination:'Destination folder', archive:'Archive destination', trash:'Trash destination', notesColumn:'Notes', emptyMapping:'No user labels; you can continue.', invalidFolder:'Folder names must not be blank or contain control characters.', collision:'Folder names collide after case, Unicode and surrounding-whitespace normalization.', reservedFolder:'User folders cannot use provider-reserved names.', specialConflict:'An Archive/Trash user label conflicts with a special-action mapping key; rename that label in the original rule first.', mappingBlocked:'Fix folder mappings before exporting.',
  exportTitle:'Export migration materials', exportHelp:'Downloading does not complete migration. Create folders, review the report, test matching and nonmatching messages, then enable rules.', active:'Converted rules', disabled:'Disabled or skipped', sieve:'Download rules.sieve', folderDownload:'Download folders.json', senderDownload:'Download senders.csv', gaps:'Download gaps.md', recipe:'Download manual recipe', guide:'Download migration guide', copy:'Copy Sieve', copied:'Copied', copyFailed:'Copy failed; download the file instead.', noActive:'No directly enabled rules. The Sieve file may contain comments only; read the report.', recipeHelp:'This destination uses a manual recipe, not an importable Sieve script.',
  footer:'No mailbox login, uploads or automatic mailbox changes. Current analysis is not saved when this page closes.',
};
export function t(lang, key) { return (lang === 'en' ? en : zh)[key] ?? key; }
